config/routes.rb
Rails.application.routes.draw do
  
  resources :notes
  resources :users
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to:'sessions#destroy'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  # scope :by_user, -> (id) { includes(:user).where("users.id": id).references(:user) if id.present? }
  scope :by_type, -> (type) { where(note_type: type) if type.present? }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # include SessionsHelper

  helper_method :current_user, :logged_in?

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def require_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_logged_in
  before_action :set_note, only: [:edit, :show, :update, :destroy]

  def index
    @notes = current_user.notes.by_type(params[:note_type])
  end

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      flash[:success] = "创建成功。"
      redirect_to notes_url
    else
      flash[:danger] = "创建失败。"
      render :new
    end
  end

  def update
    if @note.update_attributes(note_params)
      flash[:success] = "更新成功。"
      redirect_to edit_note_url(@note)
    else
      flash[:danger] = "更新失败。"
      render :edit
    end
  end

  def destroy
    if @note.destroy
      flash[:success] = "删除成功。"
      redirect_to notes_url
    end
  end

  def show
    if current_user.id == @note.user.id
      render "show"
    else
      redirect_to notes_url
    end
  end

  def edit
    if current_user.id == @note.user.id
      render "edit"
    else
      redirect_to notes_url
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :body, :latlng, :note_type)
  end

  def set_note
    @note = Note.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to notes_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, except: [:new]
  before_action :set_user, only: [:edit, :show, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "注册成功。"
      redirect_to root_url
    else
      flash[:danger] = "注册失败。"
      render :new
    end
  end

  def show

  end

  def edit
    if current_user.id == @user.id
      render :edit
    else
      redirect_to root_url
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "更新成功。"
      redirect_to root_url
    else
      flash[:danger] = "更新失败。"
      render :edit
    end
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def datetime(datetime)
    datetime.strftime('%Y年%m月%d日 %H点%M分') if datetime
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MapNate", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "笔记", notes_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "users", users_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
          <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
          </ul>
          </li>
          <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type,message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert">×</button>
        </div>
      <% end %>
    </div>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for(@note, class: "form-inline") do |f| %>
  <%= f.input :title, label: "主题", class: "form-control" %>
  <%= f.input :note_type, label: "标签", class: "form-control" %>
  <%= f.input :body, label: "内容", as: :text, class: "form-control" %>
  <%= f.input :latlng, label: "经纬度", class: "form-control" %>
  <button type="button" name="确定", id="locate">确定</button>
  <button type="button" name="重置", id="reset">重置</button>
  <%= f.button "submit", class: "btn btn-primary btn-block" %>
<% end %>

app/views/notes/edit.html.erb
<div class="container">
  <div class="col-lg-6 col-lg-offset-3">
    <div id="map_edit">

    </div>
    <%= render 'form' %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    var map = L.map('map_edit').setView([<%= @note.latlng %>], 8);
    var position = [];
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.marker([<%= @note.latlng %>]).addTo(map)
        .bindPopup("当前位置 " + "LatLng(<%= @note.latlng %>)")
        .openPopup();
    function onLocationFound(e) {
      var marker = L.marker(e.latlng, {draggable: true})
              .addTo(map)
              .bindPopup("你点击的位置在 " + e.latlng)
              .on('dragend', function (event) {
                var lat = marker.getLatLng().lat;
                var lng = marker.getLatLng().lng;
                position.push([lat, lng]);
              });
            marker.on('mouseover', function (e) {
              this.bindPopup("你点击的位置在 " + e.latlng)
              this.openPopup();
            })
            marker.on('mouseout', function (e) {
              this.closePopup();
            })

      }
    map.on('click', onLocationFound);
    $('#locate').click(function () {
        var latlng =  position[position.length-1];
        $('#note_latlng').val(latlng);
      });
    $('#reset').click(function () {
        var latlng = [];
        $('#note_latlng').val(latlng);
      });
  });

</script>

app/views/notes/index.html.erb
<% provide(:title, "Note") %>
<% if current_user %>
  <div class="container">
    <div class="col-lg-6 col-lg-offset-3">
      <%= link_to "New Note", new_note_path, class: "btn btn-primary" %>
      <%= link_to "All Note", notes_path, class: "btn btn-success" %>
      <table class="table table-bordered">
        <tr>
          <th>#</th>
          <th>主题</th>
          <th>标签</th>
          <th>内容</th>
          <th>创建时间</th>
          <th>更新时间</th>
          <th>编辑</th>
        </tr>
        <% @notes.each do |note| %>
        <tr>
          <td><%= note.id %></td>
          <td><%= note.title %></td>
          <td><%= note.note_type %></td>
          <td><%= note.body %></td>
          <td><%= datetime note.created_at %></td>
          <td><%= datetime note.updated_at %></td>
          <td>
            <% if current_user == note.user %>
              <%= link_to "edit", edit_note_path(note) %>
              <%= link_to "delete", note, method: :delete, data: { confirm: "确定删除？" }  %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-lg-6 col-lg-offset-3">
    <div id="map_index">
    </div>
  </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    var map = L.map('map_index').setView([29.86, 121.56], 8);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    <% @notes.each do |note| %>
      L.marker([<%= note.latlng %>])
               .bindPopup("<label>用户名:</label> <%= note.user.name %></br>" +
                          "<label>主题:</label> <%= note.title %><br>" +
                          "<label>标签:</label> <a href='/notes?note_type=<%= note.note_type %>'><%= note.note_type %></a><br>" +
                          "<label>内容:</label> <%= note.body %><br>" +
                          "<label>创建时间:</label> <%= datetime note.created_at %></br>" +
                          "<label>更新时间:</label> <%= datetime note.updated_at %></br>" +
                          "<% if current_user.id == note.user.id %>" +
                            "<a href='/notes/<%= note.id %>/edit'>edit</a>" +
                            "<a data-confirm='确定删除' rel='nofollow' data-method='delete' href='/notes/<%= note.id %>'> delete</a>" +
                          "<% end %>")
               .addTo(map);
    <% end %>
  });
</script>

app/views/notes/new.html.erb
<%= javascript_include_tag 'map', 'data-turbolinks-track' => true %>

<div class="container">
  <div class="col-lg-6 col-lg-offset-3">
    <div id="map_new">

    </div>
    <%= render 'form' %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    var map = L.map('map_new').setView([29.86, 121.56], 8);
    var position = [];
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.marker([29.86, 121.56]).addTo(map)
        .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
        .openPopup();
    function onLocationFound(e) {
      var marker = L.marker(e.latlng, {draggable: true})
              .addTo(map)
              .bindPopup("你点击的位置在 " + e.latlng)
              .on('dragend', function (event) {
                var marker = event.target;
                var lat = marker.getLatLng().lat;
                var lng = marker.getLatLng().lng;
                position.push([lat, lng]);
              });
            marker.on('mouseover', function (e) {
              this.bindPopup("你点击的位置在 " + e.latlng)
              this.openPopup();
            })
            marker.on('mouseout', function (e) {
              this.closePopup();
            })
      }
    map.on('click', onLocationFound);
    $('#locate').click(function () {
        var latlng =  position[position.length-1];
        $('#note_latlng').val(latlng);
      });
    $('#reset').click(function () {
        var latlng =  [];
        $('#note_latlng').val(latlng);
      });
  });
</script>

app/views/notes/show.html.erb
<% provide(:title, "#{@note.title}") %>

<div class="container">
  <div class="col-lg-6 col-lg-offset-3">
    <ul>
      <li><label>主题：</label><%= @note.title %></li>
      <li><label>标签：</label><%= @note.note_type %></li>
      <li><label>内容：</label><%= @note.body %></li>
    </ul>
  </div>
</div>

app/views/pages/index.html.erb
<% provide(:title, "MapNote") %>

<div class="part-1">
  <div class="block-1">
    <h1>享受大脑升级的快感</h1>
    <h2>10分钟读完一本好书，获取最精华的内容，让你快速涉猎最多的知识领域</h2>
    <div class="block-1-button">
      <%= link_to '立即体验', notes_path %>
    </div>
  </div>
</div>
<div class="part-2">
  <div class="block-2">
    <h3>厚重英文书再也不是梦魇</h3>
    <div class="block-p">
      <p>
        浓缩书精选优质英文好书，提炼原书精华。每天10分钟，与世界顶级精英对话，升级你的认知，以全新的思维审视世界。
      </p>
    </div>
    <div class="block-2-1">
      <div class="picture"><%= image_tag '2.jpg' %></div>
      <h3>精选英文书籍</h3>
      <p>
        我们精选英文世界最优质书籍，由专业团队对内容进行浓缩、翻译。无需掌握英文，也可阅读最前沿的知识。
      </p>
    </div>
    <div class="block-2-1">
      <div class="picture"><%= image_tag '3.jpg' %></div>
      <h3>突出重点，聚焦精华</h3>
      <p>
        清晰的逻辑是浓缩书的标配。每本浓缩书都会有理有据有条理地为您呈现全书的精华观点。
      </p>
    </div>
    <div class="block-2-1">
      <div class="picture"><%= image_tag '4.jpg' %></div>
      <h3>享受流畅阅读的快感</h3>
      <p>
        浓缩书会突出全书最精华的内容，同时用最接地气的表达保证您的流畅阅读体验。
      </p>
    </div>
  </div>
</div>
<div class="part-3">
  <div class="block-3">
    <h3>我们的优质书籍有</h3>
    <div class="books">
      <div class="books-1">
        <div class="thumb">
          <%= image_tag 'book1.jpg' %>
        </div>
      </div>
      <div class="books-1">
        <div class="thumb">
          <%= image_tag 'book2.jpg' %>
        </div>
      </div>
      <div class="books-1">
        <div class="thumb">
          <%= image_tag 'book3.jpg' %>
        </div>
      </div>
      <div class="books-1">
        <div class="thumb">
          <%= image_tag 'book4.jpg' %>
        </div>
      </div>
      <div class="books-1">
        <div class="thumb">
          <%= image_tag 'book5.jpg' %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="part-4">
  <div class="block-4">
    <h3>还等什么赶紧注册!</h3>
    <div class="block-4-button">
      <%= link_to '立即注册', signup_path %>
    </div>
  </div>
  <div class="site-footer">
    <footer id="footer" class="site-footer col-md-12 col-md-offset-0">
      <div class="def-footer">
        <div class="help-link">
          <ul class="list-inline">
            <li><%= link_to '关于我们', '#' %></li>
            <li><%= link_to '联系我们', '#' %></li>
            <li><%= link_to '情非得已', '#' %></li>
            <li><%= link_to '新生大学', '#' %></li>
            <li><%= link_to '风利', '#' %></li>
          </ul>
        </div>
        <div class="copyright-info">
          <span>©2016 浓缩书, Inc. All Rights Reserved</span>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for(@user, class: "form-inline") do |f| %>
      <%= f.input :name, label: "名字", class: "form-control" %>
      <%= f.input :email, label: "邮箱", class: "form-control" %>
      <%= f.input :password, label: "密码", class: "form-control" %>
      <%= f.input :password_confirmation, label: "确认密码", class: "form-control" %>
      <%= f.button "submit", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, "用户列表") %>

<div class="container">
  <div class="col-lg-6 col-lg-offset-3">
    <table class="table table-bordered">
      <tr>
        <th>#</th>
        <th>用户名</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <% if current_user.id == user.id %>
              <%= link_to user.name, notes_path %>
            <% else %>
              <%= user.name %>
            <% end %>
          </td>
        </tr>
        <% end %>
    </table>

  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>